---
- name: start the tomcat server
  hosts: 172.31.35.31
  become: yes
  tasks:
    - name: installation of apache2 -y
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: Install  PHP
      apt: 
        name: php
        state: present    
    - name: install libapache2-mod-php
      apt:
        name: libapache2-mod-php
        state: present 
    - name: install php-mysql
      apt:
        name: php-mysql
        state: presnt
    - name: install php-cli-y
      apt:
        name: php-cli-y
        state: present 
    - name: create a file
      ansible.builtin.copy:
        src: lampserver.service
        dest: /var/www/html/info.php  
    - name: restart apache2
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        state: started
                
 