---
- name: SpringPetClinicPractice
  hosts: 172.31.35.31
  become: yes
  tasks:
    - name: Installation of open-JDK
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: Create Springpetclinic directory
      ansible.builtin.file:
        path: /usr/share/springpetclinic
        state: directory
    - name: Get url from source
      get_url:
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic
    - name: Create springpetuser
      ansible.builtin.user:
        name: springbootuser
        password: springbootuser
        state: present 
    - name: Change ownership of the folder
      ansible.builtin.file:
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser
        mode: '500'
        state: file
    - name: copy a file
      ansible.builtin.copy:
        src: springpetclinic.service
        dest: /etc/systemd/system/springpetclinic.service
    - name: Enable and start springpetclinic srvice 
      ansible.builtin.systemd:
        name: springpetclinic.service
        enabled: yes
        state: started    

                

        